# Site settings
title: PRIMES BA Documentation
author:
  name: GDS - PDSS - BA Team
  email: your-email@domain.com
description: "PRIMES BA Team - Documentation"

# Build settings
remote_theme: jekyll/minima
