# Site settings
title: PRIMES BA Documentation
author:
  name: GDS - PDSS - BA Team
  email: your-email@domain.com
description: "PRIMES BA Team - Documentation"

# Site subpath, e.g. /blog
baseurl: "/PRIMES-Doc"


# Site base hostname & protocol, e.g. http://example.com
url: "https://unhcrdata.github.io/PRIMES-Doc/index.html"

# Build settings
remote_theme: jekyll/minima


